GET http://localhost:3000/api/v1/empleados HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTkyMDMzNCwiZXhwIjoxNzQ5OTIzOTM0fQ.7WrNTfgL30h4Xm-MfIjkZ9UELTorO-RHZ5gJ21haeZE


###

GET http://localhost:3000/api/v1/empleados/976306e2-8708-4cda-a9a3-a638fe442995 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTc4OTgxOCwiZXhwIjoxNzQ5NzkzNDE4fQ.8BFpK5pgWvJ-ULc7SCvsRa1EqoCkkc6W26nax1gfnBk

###

POST http://localhost:3000/api/v1/empleados  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTc4OTgxOCwiZXhwIjoxNzQ5NzkzNDE4fQ.8BFpK5pgWvJ-ULc7SCvsRa1EqoCkkc6W26nax1gfnBk

{
        "correo": "profesor@gmail.com",
        "cedula": "123456789",
        "nombre": "Profesor apellido1 apellido2",
        "telefono": "12345678",
        "carrera": "Informática Empresarial"

}

###

PATCH  http://localhost:3000/api/v1/empleados/976306e2-8708-4cda-a9a3-a638fe442995  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTc4OTgxOCwiZXhwIjoxNzQ5NzkzNDE4fQ.8BFpK5pgWvJ-ULc7SCvsRa1EqoCkkc6W26nax1gfnBk

{

        "correo": "profesor@gmail.com",
        "cedula": "123456789",
        "nombre": "Profesor apellido1 apellido2",
        "telefono": "12345678",
        "carrera": "Economía Agrícola"
        
}

###

POST http://localhost:3000/api/v1/empleados/registro-empleado  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTgwNzI1OSwiZXhwIjoxNzQ5ODEwODU5fQ.nXC0HH_kY645ILjP6tcHNNz-YiiWfaEwR1SIizDrON0

{
        "usuario": "empleado1",
        "password": "1234",
        "correo": "empleado1@gmail.com",
        "nombreRol": "profesor",
        "cedula": "123456789",
        "nombre": "Profesor apellido1 apellido2",
        "telefono": "11111111",
        "carrera": "Informática Empresarial"

}

###


PATCH  http://localhost:3000/api/v1/empleados/usuario-empleado/3e8bf2c3-f7ce-40c6-8e5d-8977c55c9d7c  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTkyMDMzNCwiZXhwIjoxNzQ5OTIzOTM0fQ.7WrNTfgL30h4Xm-MfIjkZ9UELTorO-RHZ5gJ21haeZE

{
        "usuario": "empleado",
        "password": "1234",
        "correo": "empleado@gmail.com",
        "nombreRol": "profesor",
        "cedula": "123456789",
        "nombre": "Profesor apellido1 apellido2",
        "telefono": "11111111",
        "carrera": "Informática Empresarial"

}

###

DELETE http://localhost:3000/api/v1/empleados/976306e2-8708-4cda-a9a3-a638fe442995 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjoiZm9mbyIsImNvcnJlbyI6ImZvZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc0OTc4OTgxOCwiZXhwIjoxNzQ5NzkzNDE4fQ.8BFpK5pgWvJ-ULc7SCvsRa1EqoCkkc6W26nax1gfnBk
