GET http://localhost:3000/api/v1/empleados HTTP/1.1

###

GET http://localhost:3000/api/v1/empleados/ca696a4c-0e47-43c1-826e-a4e4b440d7ad HTTP/1.1

###

POST http://localhost:3000/api/v1/empleados  HTTP/1.1
content-type: application/json

{
        "correo": "profesor@gmail.com",
        "cedula": "123456789",
        "nombre": "Rodolfo",
        "telefono": "44444444",
        "carrera": "Informática Empresarial",
        "borradoLogico": false,
        "createdInfo": "fofo"

}

###

PATCH  http://localhost:3000/api/v1/empleados/ca696a4c-0e47-43c1-826e-a4e4b440d7ad  HTTP/1.1
content-type: application/json

{

        "correo": "profesor@gmail.com",
        "cedula": "123456789",
        "nombre": "Rodolfo Méndez",
        "telefono": "12345678",
        "carrera": "Economía Agrícola",
        "updatedInfo": "fofo"
        
}

###

DELETE http://localhost:3000/api/v1/empleados/ca696a4c-0e47-43c1-826e-a4e4b440d7ad HTTP/1.1
